### ISSUE TITLE
Answer the questions written in questions.txt file

### ISSUE THREAD

**Issue by Samiullah-Kalhoro** [Samiullah-Kalhoro/hacktoberfest_21#11]

**Comment by Harshit-Poddar90** [comment]
what do we need to do in this?

**Comment by Samiullah-Kalhoro** [comment]
you can answer anyone question written in questions.odt file

**Comment by Samiullah-Kalhoro** [comment]
I have uploaded a new questions.txt file due to some conflicts with.odt format

**Comment by nilanshijain** [comment]
I have added answer for question 3 in questions.txt !!

**Comment by RESHU-05** [comment]
What I can do in this issue now?

**Comment by Samiullah-Kalhoro** [comment]
@RESHU-05 you can add more coding-based questions for beginners into the questions.txt file.

**Comment by mrdowneyjr** [comment]
please assign it to me

**Comment by komalinandamuri** [comment]
Is there any issues i want to fix something
