### ISSUE TITLE
I would like to submit solution to this problem. Please assign this to me.

### ISSUE THREAD

**Issue by Preranasingh2001** [Samiullah-Kalhoro/hacktoberfest_21#137]
https://github.com/Samiullah-Kalhoro/hacktoberfest_21/blob/22a3ed6af00237459f7522d8bca3d87da491a8de/Questions.txt#L329

**Comment by mrdowneyjr** [comment]
i want to solve this problem

**Comment by som-bit** [comment]
I can Solve this problem in Java. Please assign me to this problem.

**Comment by kasyap1234** [comment]
I would like to solve this problem in both c++ and python . 
Please assign me this problem .

**Comment by UtkarshSiddhpura** [comment]
`
static int sum(){
		int summation = 0;
		for (int i = 151; i < 290; i++) {
			if(i % 3 == 0){
				summation += i;
			}
		}
		return summation;
	}
`

**Comment by UtkarshSiddhpura** [comment]
`static int sum(){`
		`int summation = 0;`
		`for (int i = 151; i < 290; i++) {`
			`if(i % 3 == 0){`
				`summation += i;`
			`}`
		`}`
		`return summation;`
	}`

**Comment by UtkarshSiddhpura** [comment]
```static int sum(){
		int summation = 0;
		for (int i = 151; i < 290; i++) {
			if (i % 3 == 0) {
				summation += i;
			}
		}
		return summation;
	}```

**Comment by UtkarshSiddhpura** [comment]
~~~ 
static int sum(){
		int summation = 0;
		for (int i = 151; i < 290; i++) {
			if(i % 3 == 0){
				summation += i;
			}
		}
		return summation;
	}
