### ISSUE TITLE
Python: Division

### ISSUE THREAD

**Issue by Harshit-Poddar90** [Samiullah-Kalhoro/hacktoberfest_21#14]
The provided code stub reads two integers,  and , from STDIN.

Add logic to print two lines. The first line should contain the result of integer division,  // . The second line should contain the result of float division a/b

No rounding or formatting is necessary.

**Comment by Harshit-Poddar90** [comment]
pls assign to me.

**Comment by snehadaripa** [comment]
please assign this to me.
