### ISSUE TITLE
What's Your Name?

### ISSUE THREAD

**Issue by Harshit-Poddar90** [Samiullah-Kalhoro/hacktoberfest_21#62]
You are given the firstname and lastname of a person on two different lines. Your task is to read them and print the following:

Hello firstname lastname! You just delved into python.

Function Description

Complete the print_full_name function in the editor below.

print_full_name has the following parameters:

string first: the first name
string last: the last name

**Comment by Harshit-Poddar90** [comment]
pls assign it to me.

**Comment by Adityan2001** [comment]
My name is Adityan Gupta.
